fix: Give the statemachine interval values a small default int value
The previous setup had an empty string as the default value, which will lead to
an error in the timeutils, which are expecting an int.

```
  File "/usr/lib/python3.8/site-packages/mender/util/timeutil.py", line 28, in get_next
    return datetime.now() + timedelta(0, self.interval_seconds)
TypeError: unsupported type for timedelta seconds component: str
```

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>